version: '3'
services:
  db:
    image: postgres:16.0-alpine3.17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    container_name: db
    ports:
      - "${DB_PORT}:5432"
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "3030:8080"
volumes:
  postgresdb-data:
