version: '3'
services:
  db:
    image: postgres:16.0-alpine3.17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    container_name: db
    ports:
      - "${DB_PORT}:5432"
  app:
    build:
      context: .
      target: final
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    depends_on:
      - db
volumes:
  postgresdb-data:
